seed: 42

data:
  root: 'project/data/images'
  train_ratio: 0.7
  val_ratio: 0.2
  batch_size:
    train: 64
    test: 32
  num_workers: 4
  pin_memory: True
  transform_train:
    resize: [224, 224]
    random_horizontal_flip: True
    random_rotation: 10
    normalize: 
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  transform_val_test: 
    resize: [224,224]
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

model: 
  architecture: 'efficientformer_l1'
  pretrained: True
  num_classes: null

training:
  initial_lr: 0.001
  batch_size_scale: 256
  num_epochs: 10
  patience: 3
  save_path: 'project/models/best_model.pth'
  initial_scale: 65536     
  growth_factor: 2.0        
  backoff_factor: 0.5       

scheduler:
  type: 'cosine'
  warmup_epochs: 5
  min_lr: 0.000001